on:
  push:
    branches:
      - main

jobs:
  ghidra:
    runs-on: macos-13
    permissions: write-all

    steps:
      - uses: actions/checkout@v4
        with:
          repository: NationalSecurityAgency/ghidra
          ref: master

      - name: Show versions
        run: |
          uname -a
          sw_vers
          xcodebuild -version
          system_profiler SPHardwareDataType

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup ghidra dependencies
        run: |
          gradle --quiet --init-script gradle/support/fetchDependencies.gradle

      - name: Build ghidra
        run: |
          gradle --build-cache --parallel --warning-mode none buildGhidra

      - uses: actions/upload-artifact@v4
        with:
          name: ghidra
          path: build/dist/
          retention-days: 1
          include-hidden-files: true
