on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ghidra:
    strategy:
      fail-fast: true
      matrix:
        runner:
          - macos-15-large # macOS 15 Intel: https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md
          - macos-26-xlarge # macOS 26 Arm64: https://github.com/actions/runner-images/blob/main/images/macos/macos-26-arm64-Readme.md

    runs-on: ${{ matrix.runner }}
    permissions: write-all

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v5
        with:
          repository: NationalSecurityAgency/ghidra
          ref: master

      - name: Show versions
        run: |
          uname -a
          sw_vers
          xcodebuild -version
          system_profiler SPHardwareDataType

      # https://github.com/actions/setup-java
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          check-latest: true
          cache: 'gradle'

      # # https://github.com/gradle/actions
      # - name: Setup Gradle
      #   uses: gradle/actions/setup-gradle@v4

      - name: Setup ghidra dependencies
        run: |
          ./gradlew --quiet --init-script gradle/support/fetchDependencies.gradle

      - name: Build ghidra
        run: |
          ./gradlew --build-cache --no-parallel --warning-mode none buildGhidra

      - uses: actions/upload-artifact@v4
        with:
          name: ghidra-${{ runner.arch }}
          path: build/dist/
          retention-days: 1
          include-hidden-files: true
